### ISSUE TITLE
Failed to sync data

### ISSUE THREAD

**Issue by lzxm160** [iotexproject/iotex-analytics#109]
using commit https://github.com/iotexproject/iotex-analytics/commit/800215b6fa7131abef1c1295803126f841cc80c2 and mainnet endpoint
need find out the reason

FATAL	iotex-analytics/main.go:127	Failed to start the indexer   {"error": "failed to index blocks in batch: failed to build index for the block: failed to build index for block on height 1: failed to get rawdata from election service in epoch 1: failed to get rawdata: rpc error: code = Unimplemented desc = unknown method getRawData for service api.APIService", "errorVerbose": "rpc error: code = Unimplemented desc = unknown method getRawData for service api.APIService\nfailed to get rawdata\ngithub.com/iotexproject/iotex-analytics/indexprotocol/votings.(*Protocol).getRawData\n\t/root/iotex-analytics/indexprotocol/votings/protocol.go:384\ngithub.com/iotexproject/iotex-analytics/indexprotocol/votings.(*Protocol).HandleBlock\n\t/root/iotex-analytics/indexprotocol/votings/protocol.go:226\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).buildIndex.func1\n\t/root/iotex-analytics/indexservice/indexer.go:257\ngithub.com/iotexproject/iotex-analytics/sql.(*storeBase).Transact\n\t/root/iotex-analytics/sql/storebase.go:120\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).buildIndex\n\t/root/iotex-analytics/indexservice/indexer.go:255\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).IndexInBatch\n\t/root/iotex-analytics/indexservice/indexer.go:217\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).Start\n\t/root/iotex-analytics/indexservice/indexer.go:93\nmain.main\n\t/root/iotex-analytics/main.go:126\nruntime.main\n\t/root/go/src/runtime/proc.go:200\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337\nfailed to get rawdata from election service in epoch 1\ngithub.com/iotexproject/iotex-analytics/indexprotocol/votings.(*Protocol).HandleBlock\n\t/root/iotex-analytics/indexprotocol/votings/protocol.go:228\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).buildIndex.func1\n\t/root/iotex-analytics/indexservice/indexer.go:257\ngithub.com/iotexproject/iotex-analytics/sql.(*storeBase).Transact\n\t/root/iotex-analytics/sql/storebase.go:120\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).buildIndex\n\t/root/iotex-analytics/indexservice/indexer.go:255\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).IndexInBatch\n\t/root/iotex-analytics/indexservice/indexer.go:217\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).Start\n\t/root/iotex-analytics/indexservice/indexer.go:93\nmain.main\n\t/root/iotex-analytics/main.go:126\nruntime.main\n\t/root/go/src/runtime/proc.go:200\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337\nfailed to build index for block on height 1\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).buildIndex.func1\n\t/root/iotex-analytics/indexservice/indexer.go:258\ngithub.com/iotexproject/iotex-analytics/sql.(*storeBase).Transact\n\t/root/iotex-analytics/sql/storebase.go:120\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).buildIndex\n\t/root/iotex-analytics/indexservice/indexer.go:255\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).IndexInBatch\n\t/root/iotex-analytics/indexservice/indexer.go:217\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).Start\n\t/root/iotex-analytics/indexservice/indexer.go:93\nmain.main\n\t/root/iotex-analytics/main.go:126\nruntime.main\n\t/root/go/src/runtime/proc.go:200\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337\nfailed to build index for the block\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).IndexInBatch\n\t/root/iotex-analytics/indexservice/indexer.go:218\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).Start\n\t/root/iotex-analytics/indexservice/indexer.go:93\nmain.main\n\t/root/iotex-analytics/main.go:126\nruntime.main\n\t/root/go/src/runtime/proc.go:200\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337\nfailed to index blocks in batch\ngithub.com/iotexproject/iotex-analytics/indexservice.(*Indexer).Start\n\t/root/iotex-analytics/indexservice/indexer.go:94\nmain.main\n\t/root/iotex-analytics/main.go:126\nruntime.main\n\t/root/go/src/runtime/proc.go:200\nruntime.goexit\n\t/root/go/src/runtime/asm_amd64.s:1337"}

**Comment by koseoyoung** [comment]
our latest commit is not compatible with current mainNet yet, analytics' update is dependent with core/election version upgrade

**Comment by lzxm160** [comment]
> our latest commit is not compatible with current mainNet yet, analytics' update is dependent with core/election version upgrade

Is it compatible with testnet? if not,how can I test code?

**Comment by koseoyoung** [comment]
@lzxm160 yes this is compatible with testNet where core version is  v0.9.0

**Comment by koseoyoung** [comment]
@lzxm160 yes it is compatible with testnet right now (v0.9.0) which I'm testing for native staking, but I think over than 0.8.3 is fine

**Comment by lzxm160** [comment]
> @lzxm160 yes it is compatible with testnet right now (v0.9.0) which I'm testing for native staking, but I think over than 0.8.3 is fine to be compatible with latest commit

Thanks,I'll try testnet later
