### ISSUE TITLE
Dynamic pagination parsing is not working

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-analytics#135]
![511573625262_ pic_hd](https://user-images.githubusercontent.com/15241597/68738619-a2587f80-059b-11ea-86c0-3e7099284ca5.jpg)

**Comment by lzxm160** [comment]
query contractActions($address: String!, $pagination:Pagination!) {
  action{
    evmTransfersByAddress(address: $address){
      count
      evmTransfers(pagination: $pagination) {
        from
        to
        quantity
        actHash
        blkHash
        timeStamp
      }
    }
  }
}

{
  "address":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m",
  "pagination":{
"first":10,
"skip":0
}
}

**Comment by lizhefeng** [comment]
> query contractActions($address: String!, $pagination:Pagination!) {
> action{
> evmTransfersByAddress(address: $address){
> count
> evmTransfers(pagination: $pagination) {
> from
> to
> quantity
> actHash
> blkHash
> timeStamp
> }
> }
> }
> }
> 
> {
> "address":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m",
> "pagination":{
> "first":10,
> "skip":0
> }
> }

It works now. Thanks!
