### ISSUE TITLE
gql endpoint should return json

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-analytics#143]
![71574813305_ pic](https://user-images.githubusercontent.com/1387285/69682662-ff0d6d00-1066-11ea-8a34-1fdecc575c8d.jpg)
![81574813306_ pic](https://user-images.githubusercontent.com/1387285/69682664-016fc700-1067-11ea-874f-8828762b96d3.jpg)

**Comment by lzxm160** [comment]
Test is good for curl:

curl 'https://analytics.iotexscan.io/query'  --data-binary '{"query":"# Write your query or mutation here\nquery contractActions($address: String!, $pagination:Pagination!) {\n  action{\n    evmTransfersByAddress(address: $address){\n      count\n      evmTransfers(pagination: $pagination) {\n        from\n        to\n        quantity\n        actHash\n        blkHash\n        timeStamp\n      }\n    }\n  }\n}\n","variables":{"address":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","pagination":{"first":10,"skip":0}}}' -v
*   Trying 104.27.144.89...
*   Trying 2606:4700:30::681b:9159...
* Immediate connect fail for 2606:4700:30::681b:9159: Network is unreachable
*   Trying 2606:4700:30::681b:9059...
* Immediate connect fail for 2606:4700:30::681b:9059: Network is unreachable
* Connected to analytics.iotexscan.io (104.27.144.89) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: iotexscan.io (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC
* 	 certificate version: #3
* 	 subject: C=US,ST=CA,L=San Francisco,O=CloudFlare\, Inc.,CN=iotexscan.io
* 	 start date: Mon, 27 May 2019 00:00:00 GMT
* 	 expire date: Wed, 27 May 2020 12:00:00 GMT
* 	 issuer: C=US,ST=CA,L=San Francisco,O=CloudFlare\, Inc.,CN=CloudFlare Inc ECC CA-2
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> POST /query HTTP/1.1
> Host: analytics.iotexscan.io
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 460
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 460 out of 460 bytes
< HTTP/1.1 200 OK
< Date: Tue, 10 Dec 2019 02:00:19 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=dd351025f31f7b64a665ea5bede79309f1575943219; expires=Thu, 09-Jan-20 02:00:19 GMT; path=/; domain=.iotexscan.io; HttpOnly; Secure
< Access-Control-Allow-Headers: *
< Access-Control-Allow-Origin: *
< Via: 1.1 vegur
< CF-Cache-Status: DYNAMIC
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 542b9fe10b8ee50e-LAX
< 
{"data":{"action":{"evmTransfersByAddress":{"count":184,"evmTransfers":[{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"9b802134ba04e174b2da596d2ee6a2bd1c5ebb2bd2a26c56178f9958d774f65f","blkHash":"2159278","timeStamp":1575936095},{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"8842975b56e67c1b5d44a0b654bc42380821752c5970698b68a1c5ee808dc8c8","blkHash":"2142003","timeStamp":1575849710},{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"eccdcec377feeb134f9297f591142492bf849dbdded54e4913f71ed69d528388","blkHash":"2124706","timeStamp":1575763225},{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"8b608844066863bb3b4f9e0f788dae4597d5eaa139e3fcd24af33c2fee4c19b5","blkHash":"2107498","timeStamp":1575676890},{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"ed8cb9a92abcbc01bd47b3aa0963ddf6ba55a7e80d6a851549ac160e06eaf427","blkHash":"2090337","timeStamp":1575590500},{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"289d2dcac450c410e4dac77092a646d8fccb881e563e44819ab300d181eaa05d","blkHash":"2073201","timeStamp":1575504630},{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"b33fdf7723b1b9277073635dd1dab852b50b989f706aed32e47d19f7cf106d05","blkHash":"2055810","timeStamp":1575417620},{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"0483fe85ff1d9a2106ae4ef90f4f88f975558e7cf96bec3962f688cc965d3af3","blkHash":"2038531","timeStamp":1575331225},{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2* Connection #0 to host analytics.iotexscan.io left intact
wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"823b223f8dd40702f513c77d19a2e4c5cc94626617352d28428f06c2142a2183","blkHash":"2021286","timeStamp":1575244930},{"from":"io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m","to":"io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw","quantity":"0","actHash":"1c6c8b5bba3e81229f1afef8745f895b887ba19a0ece0ac1ed039fb1e2954747","blkHash":"2004005","timeStamp":1575158480}]}}}}

I think maybe that the way using apollo is not right,could try adding request header 'Content-Type: application/json'

**Comment by guoxiaopang** [comment]
![image](https://user-images.githubusercontent.com/11028035/70605563-b85a6e00-1c35-11ea-95ef-b71a4078df2a.png)

**Comment by guoxiaopang** [comment]
![image](https://user-images.githubusercontent.com/11028035/70605583-c01a1280-1c35-11ea-93f4-b62658735e99.png)

**Comment by guoxiaopang** [comment]
I tried adding headers but it didn't work

**Comment by guoxiaopang** [comment]
<!DOCTYPE html>
<html>
<head>
	<meta charset=utf-8/>
	<meta name="viewport" content="user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui">
	<link rel="shortcut icon" href="https://graphcool-playground.netlify.com/favicon.png">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.20/build/static/css/index.css" 
		integrity="sha256-cS9Vc2OBt9eUf4sykRWukeFYaInL29&#43;myBmFDSa7F/U=" crossorigin="anonymous"/>
	<link rel="shortcut icon" href="https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.20/build/favicon.png"
		integrity="sha256-GhTyE&#43;McTU79R4&#43;pRO6ih&#43;4TfsTOrpPwD8ReKFzb3PM=" crossorigin="anonymous"/>
	<script src="https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.20/build/static/js/middleware.js"
		integrity="sha256-4QG1Uza2GgGdlBL3RCBCGtGeZB6bDbsw8OltCMGeJsA=" crossorigin="anonymous"></script>
	<title>GraphQL playground</title>
</head>
<body>
<style type="text/css">
	html { font-family: "Open Sans", sans-serif; overflow: hidden; }
	body { margin: 0; background: #172a3a; }
</style>
<div id="root"/>
<script type="text/javascript">
	window.addEventListener('load', function (event) {
		const root = document.getElementById('root');
		root.classList.add('playgroundIn');
		const wsProto = location.protocol == 'https:' ? 'wss:' : 'ws:'
		GraphQLPlayground.init(root, {
			endpoint: location.protocol + '//' + location.host + '\/query',
			subscriptionsEndpoint: wsProto + '//' + location.host + '\/query',
			settings: {
				'request.credentials': 'same-origin'
			}
		})
	})
</script>
</body>
</html>

**Comment by guoxiaopang** [comment]
<!DOCTYPE html>
<html>
<head>
	<meta charset=utf-8/>
	<meta name="viewport" content="user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui">
	<link rel="shortcut icon" href="https://graphcool-playground.netlify.com/favicon.png">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.20/build/static/css/index.css" 
		integrity="sha256-cS9Vc2OBt9eUf4sykRWukeFYaInL29&#43;myBmFDSa7F/U=" crossorigin="anonymous"/>
	<link rel="shortcut icon" href="https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.20/build/favicon.png"
		integrity="sha256-GhTyE&#43;McTU79R4&#43;pRO6ih&#43;4TfsTOrpPwD8ReKFzb3PM=" crossorigin="anonymous"/>
	<script src="https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.20/build/static/js/middleware.js"
		integrity="sha256-4QG1Uza2GgGdlBL3RCBCGtGeZB6bDbsw8OltCMGeJsA=" crossorigin="anonymous"></script>
	<title>GraphQL playground</title>
</head>
<body>
<style type="text/css">
	html { font-family: "Open Sans", sans-serif; overflow: hidden; }
	body { margin: 0; background: #172a3a; }
</style>
<div id="root"/>
<script type="text/javascript">
	window.addEventListener('load', function (event) {
		const root = document.getElementById('root');
		root.classList.add('playgroundIn');
		const wsProto = location.protocol == 'https:' ? 'wss:' : 'ws:'
		GraphQLPlayground.init(root, {
			endpoint: location.protocol + '//' + location.host + '\/query',
			subscriptionsEndpoint: wsProto + '//' + location.host + '\/query',
			settings: {
				'request.credentials': 'same-origin'
			}
		})
	})
</script>
</body>
</html>

**Comment by guoxiaopang** [comment]
![image](https://user-images.githubusercontent.com/11028035/70717001-6e9e8000-1d28-11ea-8032-36f2ac65dbb1.png)

**Comment by guoxiaopang** [comment]
reference      https://github.com/parse-community/parse-server/issues/166

**Comment by lizhefeng** [comment]
@guoxiaopang Is this issue resolved?

**Comment by guoxiaopang** [comment]
yes
