### ISSUE TITLE
get all tokens with pagination

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-analytics#147]
like https://etherscan.io/tokens, we need api to get all XRC20 addresses with pagination

**Comment by lzxm160** [comment]
Two ways using this:
1、
query {
  xrc20 {
    byPage(pagination:{first:3,skip:1}) {
      exist
      count
      xrc20 {
        hash
        from
        to
        quantity
        timestamp
      }
    }
  }
}
2、
query Xrc20Query($pagination:Pagination!) {
  xrc20 {
    byPage(pagination:$pagination) {
      exist
      count
      xrc20 {
        hash
        from
        to
        quantity
        timestamp
      }
    }
  }
}
query variables:
{
  "pagination":{
    "first":3,
    "skip":1
  }
}

**Comment by nmhung1210** [comment]
@lzxm160 we would need API to get all `distinct XRC20 Token addresses` not XRC20 transactions.

We would need graphQL API as below:

```
type XRC20Address {
     address: String!
}

query {
  xrc20Addresses {
    byPage(pagination:{first:3,skip:1}) {
      exist
      count
      addresses {
        address
      }
    }
  }
}
```
Could you please help to implement it at analytics services endpoint?

**Comment by lzxm160** [comment]
I misunderstood this issue, I'll add new endpoint later

**Comment by lzxm160** [comment]
using:
1、

query {
  xrc20 {
    xrc20Addresses(pagination:{first:3,skip:1}) {
      exist
      count
      addresses
    }
  }
}
2、

query Xrc20Query($pagination:Pagination!) {
  xrc20 {
    xrc20Addresses(pagination:$pagination) {
      exist
      count
     addresses
    }
  }
}
{
  "pagination":{
"first":3,
"skip":0
}
}
