### ISSUE TITLE
get all addresses holder for an xrc20 token address

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-analytics#152]
We would need APIs to get the number of holders addresses for an xrc20 token address and list of those holders addresses as well. 

```
type HolderAddress {
     address: String!
}

query {
  xrc20Holders {
    holdersCount (tokenAddress:String!) {
       count
    }
    byTokenAddress(tokenAddress:String!, pagination:{ first: Int!, skip: Int! }) {
      exist
      count
      addresses {
        address
      }
    }
  }
}
```

**Comment by lzxm160** [comment]
I'll add those api later

**Comment by lzxm160** [comment]
query {
  xrc20 {
    tokenHolderAddresses(tokenAddress:"io14j96vg9pkx28htpgt2jx0tf3v9etpg4j9h384m") {
      count
      addresses(pagination:{first:2,skip:0})
      }
    }
}
count is the total holders's count
