### ISSUE TITLE
The sum of account income should always be zero 

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-analytics#161]
We need to investigate the logic of rebuilding account inflow, account outflow, and account income table. For some epoch, the account inflow or outflow is incomplete, which results in the wrong data in account income. If we rebuild the whole three tables, everything looks correctly. Might be something wrong on the fly.

**Comment by lzxm160** [comment]
need to move action.Execution from statetracker node to analytics or adjust the time write balance_history

**Comment by lzxm160** [comment]
done with #253
