### ISSUE TITLE
Adding total records field to Xrc20List response 

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-analytics#170]
We would need an extra field named `total` for Xrc20List response. That field's value is total records of the xrc20 list (without pagination limit).

```
type Xrc20List {
   exist: Boolean!
   xrc20(...): [Xrc20Info]!
   count: Int!
   total: Int!
}
```

**Comment by lizhefeng** [comment]
We can change count to the total number of records. @lzxm160

**Comment by lzxm160** [comment]
> We can change count to the total number of records. @lzxm160

sure
