### ISSUE TITLE
Store history of kick-out status and add API to query the statistics 

### ISSUE THREAD

**Issue by koseoyoung** [iotexproject/iotex-analytics#177]
store historic kick-out list info and add API for front-end to get statistics of previous delegate kick-out info 
-- this kick-out list is one of slashing features because of underperformance for last 6 epochs 
```
type ReadStateRequest {
	protocolID 
	methodName: “KickoutListByEpoch”
	epochNum: uint64
}
type ReadStateResponse {
	date: []byte 
}
```
data is deserialized to KickoutCandidateList
https://github.com/iotexproject/iotex-proto/blob/master/proto/types/state_data.proto#L21

**Comment by lizhefeng** [comment]
We want to store the full kickout list for each epoch inside analytics by querying from ReadState API as defined above.

**Comment by koseoyoung** [comment]
also we want to give each delegate's statistics data to frontend. 
such as, in past recent ~100 epochs, if he was on blacklist for 12 epochs, then 12/100 * 100 = 12% is his kick-out rate or we can give 88(=100-12)% as performance rate

**Comment by lzxm160** [comment]
In the first step,I'll add storage and  ReadStateRequest,delegate's statistics data will be finished in the second step

**Comment by lzxm160** [comment]
I'll add storage for kickout list first and then add api

**Comment by lzxm160** [comment]
waiting for mainnet and testnet can read "KickoutListByEpoch" state

**Comment by lzxm160** [comment]
merged，wait for iotex-core‘s api ready and test

**Comment by koseoyoung** [comment]
@lzxm160 I'll lyk after deploy to testnet 
Btw, can you give me API info to query delegate's kickout historical statistics for front-end to use it?
