### ISSUE TITLE
Action byType issue

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-analytics#184]
![image](https://user-images.githubusercontent.com/6645185/77488021-9abcb780-6e66-11ea-82e7-12c8a1149836.png)

**Comment by lzxm160** [comment]
pls use:
```
query {
  action {
    byType(type:"transfer") {
      exist
      count
      actions(pagination:{first:30,skip:0}){
        actHash
        blkHash
        actType
        timeStamp
        sender
        recipient
        amount
        gasFee
      }
      }
    }
}
```

**Comment by nmhung1210** [comment]
![image](https://user-images.githubusercontent.com/6645185/78609683-69dc7980-788d-11ea-8921-50afe1cbac9f.png)

**Comment by nmhung1210** [comment]
This still not works. Could you please help recheck?

**Comment by lzxm160** [comment]
I think there's some data error in mysql,pls dump mysql data for me to check @lizhefeng

**Comment by lzxm160** [comment]
I have checked https://analytics.iotexscan.io/ with this api,the respone sometimes is good, but the response is slow,sometimes returns 503

I'll try to optimize this api later to speed up

**Comment by lizhefeng** [comment]
Still very slow. Need further investigation.

**Comment by lzxm160** [comment]
investigate further and optimize this api today
