### ISSUE TITLE
xrc20 to xrc interface change is breaking client

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-analytics#194]

**Comment by puncsky** [comment]
![31585657310_ pic](https://user-images.githubusercontent.com/1387285/78090998-915caf00-7380-11ea-8539-a9562dd7f548.jpg)
![41585657420_ pic_hd](https://user-images.githubusercontent.com/1387285/78091000-94579f80-7380-11ea-8c22-3110d4d5b2b2.jpg)
![121585705775_ pic_hd](https://user-images.githubusercontent.com/1387285/78091003-96216300-7380-11ea-8e60-590fa8491ca1.jpg)

**Comment by lzxm160** [comment]
pls tell me what is your request string
