### ISSUE TITLE
Update ReadState API deserialize method between bytes and uint64 

### ISSUE THREAD

**Issue by koseoyoung** [iotexproject/iotex-analytics#202]
According to iotex-core PR https://github.com/iotexproject/iotex-core/pull/2102, when we deserialize between bytes and uint64 to use poll/rolldpos ReadStateAPI , we decided not to use golang byteutil.BytesToUint64 but to use strconv.Parse/Format to support more general usage. This change will be deployed to testnet Easter soon

**Comment by lizhefeng** [comment]
Please make this PR based on master_testnet

**Comment by lzxm160** [comment]
done with latest master
