### ISSUE TITLE
probationHistoricalRate not work for delegates in bp list

### ISSUE THREAD

**Issue by hunglmtb** [iotexproject/iotex-analytics#216]
I tried query probationHistoricalRate data to `https://analytics.iotexscan.io/query`. It work with registered name of delegate `qvan2` (dev db)
`{startEpoch: 3885, epochCount: 4650, delegateName: "000000000000716576616e32"}` 
and response
`{"data":{"delegate":{"probationHistoricalRate":"0","__typename":"Delegate"}}}`
However, with other delegates on bp table, I got the 503 error 
![image](https://user-images.githubusercontent.com/11267061/79190088-95430380-7e4d-11ea-9307-f6cf39a496cb.png)
for example 
delegate `metanyx`
`{startEpoch: 3885, epochCount: 4650, delegateName: "00000000006d6574616e7978"}`

the query gql
```
  query probationHistoricalRate(
    $startEpoch: Int!
    $epochCount: Int!
    $delegateName: String!
  ) {
    delegate(
      startEpoch: $startEpoch
      epochCount: $epochCount
      delegateName: $delegateName
    ) {
      probationHistoricalRate
    }
  }
```
Could you help to check?

**Comment by lizhefeng** [comment]
analytics mainnet currently paused this probation history as the mainnet iotex-core has not activated the kickout API yet.
