### ISSUE TITLE
Add an API to expose delegate's reward ratio

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-analytics#227]
We want to have a new Hermes2 API:

```
hermes2(startEpoch: Int!, epochCount: Int!){
   byDelegate(delegateName: String!){
        distributionRatio: [Ratio]!
    }
}

Ratio {
    epochNumber: Int!
    blockRewardRatio: Int!
    epochRewardRatio: Int!
    foundationBonusRatio: Int!
}
```

You can find the reward ratio in column block_reward_percentage, epoch_reward_percentage, and foundation_bonus_percentage under voting_result table.

**Comment by Bharat2704** [comment]
Pull request for front end changes raised [](https://github.com/iotexproject/web-hermes/pull/73)
