### ISSUE TITLE
Add total supply and total circulating supply API

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-analytics#249]
We need to add the following APIs
```
chain {
    totalSupply String!
    totalCirculatingSupply String!
}
```
total supply = 10B - Balance(all zero address) + 2.7B (due to Postmortem 1) - Balance(nsv1) - Balance(bnfx)
total circulating = total supply  - SUM(lock addresses) - reward pool fund

**Comment by lizhefeng** [comment]
nsv1 address: io1xpq62aw85uqzrccg9y5hnryv8ld2nkpycc3gza
nsv1 balance: 262281303.94 IOTX
bnfx address: io1zn9mn4v63jg3047ylqx9nqaqz0ev659777q3xc
bnfx balance: 3414253.03 IOTX

**Comment by raullenchai** [comment]
I will provide lock addresses shortly but pls make these addresses configurable so we can add/remove later!

**Comment by lizhefeng** [comment]
reward fund (Available Balance) can be fetched from core API ReadState. Here is an example:

```
        // AvailableBalance == Rewards in the pool that has not been issued to anyone
	request := &iotexapi.ReadStateRequest{
		ProtocolID: []byte("rewarding"),
		MethodName: []byte("AvailableBalance"),
	}
	response, err := cli.ReadState(ctx, request)
	if err != nil {
		sta, ok := status.FromError(err)
		if ok {
			return output.NewError(output.APIError, sta.Message(), nil)
		}
		return output.NewError(output.NetworkError, "failed to invoke ReadState api", err)
	}
	availableRewardRau, ok := big.NewInt(0).SetString(string(response.Data), 10)
	if !ok {
		return output.NewError(output.ConvertError, "failed to convert string into big int", err)
	}
```

**Comment by raullenchai** [comment]
https://analytics.iotexscan.io/

```
query{
	chain {
    totalSupply,
    totalCirculatingSupply
  }
}
```
