### ISSUE TITLE
xrc721 interface issue 

### ISSUE THREAD

**Issue by uu-z** [iotexproject/iotex-analytics#263]
![image](https://user-images.githubusercontent.com/12439992/87749980-bf310b00-c82c-11ea-80dd-015170087ae0.png)
![image](https://user-images.githubusercontent.com/12439992/87750031-e38ce780-c82c-11ea-824b-a6ea188e4a42.png)

There is some trouble with using the above two interfaces.
This contract address (io1xpvzahnl4h46f9ea6u03ec2hkusrzu020th8xx) should have data returns on mainnet.

**Comment by guo** [comment]
related to this one: https://github.com/iotexproject/iotex-analytics/issues/252

**Comment by newyear6565** [comment]
It is related to the topic or data length in the log, let me check some docs to fix it

**Comment by newyear6565** [comment]
TODO: Synchronize xrc721 data and write to existing database
