### ISSUE TITLE
sort by timestamp issue on byType query

### ISSUE THREAD

**Issue by liaojikunwork** [iotexproject/iotex-analytics#264]
![Screen Shot 2020-07-22 at 10 48 03 AM](https://user-images.githubusercontent.com/34900782/88190876-ce3b0300-cc08-11ea-9de1-65704f8411cb.png)

https://www.iotexscan.io/action?actionType=transfer

The list of actions are not ordered by timestamp.
I can see `orderby timestamp` on the query related, but it is not working.

Reference: https://github.com/iotexproject/iotex-explorer/issues/1391
Pls notify on the issue above after fixing.

**Comment by guo** [comment]
bug is here: https://github.com/iotexproject/iotex-analytics/blob/master/queryprotocol/actions/protocol.go#L31
