### ISSUE TITLE
custom variables name search problem

### ISSUE THREAD

**Issue by uu-z** [iotexproject/iotex-analytics#266]
![WX20200725-120209](https://user-images.githubusercontent.com/12439992/88448782-b31ffb80-ce73-11ea-8e74-00ac4d0f53b4.png)
![WX20200725-120217](https://user-images.githubusercontent.com/12439992/88448783-b5825580-ce73-11ea-94ed-43032dc3982d.png)

We used a Graphlq request lib which automatically generated a custom variable name (like $v1 above) in the request. But the search result seems incorrect.

in above two requests, the $address and $v1 with the same input, but the $v1 one result was incorrect.

**Comment by newyear6565** [comment]
it still have problems
