### ISSUE TITLE
This looks wrong

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-analytics#317]
![Screen Shot 2020-12-12 at 2 49 34 PM](https://user-images.githubusercontent.com/989846/101997599-4b831500-3c89-11eb-8049-57fdd95826fe.png)

https://iotexscan.io/address/io10q6h22waxyq3s22ym83susu8la0zllcg8u9glr?locale=zh-CN

**Comment by ququzone** [comment]
this is https://github.com/iotexproject/iotex-explorer issue
