### ISSUE TITLE
Index XRC-20 token transfer

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-analytics#48]
Recognize XRC-20 transactions and index them. For example, https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52?a=0xfa93fef18d7e5d14251f7a223c5692a0ca0ad979

**Comment by raullenchai** [comment]
@lzxm160 can help on this one?

**Comment by lzxm160** [comment]
> @lzxm160 can help on this one?

sure
