### ISSUE TITLE
Partially Commit in a MySQL transaction

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-analytics#74]
We occasionally encountered the problem that a transaction of indexing a block partially commits to database while Heroku restarts. Need to figure out how to fix the problem fundamentally.

**Comment by raullenchai** [comment]
@lzxm160 pls help to investigate. 

cc @zjshen14

**Comment by lzxm160** [comment]
> @lzxm160 pls help to investigate.
> 
> cc @zjshen14

sure
