### ISSUE TITLE
Add name & symbol to the Xrc20Info type

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-analytics#88]
We would need to add `name` & `symbol` to the `Xrc20Info` type. Could you please help?

```
type Xrc20Info {
  hash: String!
  timestamp: String!
  from: String!
  to: String!
  quantity: String!
  name: String!
  symbol: String!
}
```

**Comment by lzxm160** [comment]
we didn't store those infos,I suggest call readcontract api directly

**Comment by nmhung1210** [comment]
> we didn't store those infos,can call readcontract api directly

To read a contract, we would need `contractAddress` to be added to `Xrc20Info` as response  of queries xrc20 `byPage` & `byAddress`. Could you please help recheck?

**Comment by nmhung1210** [comment]
Is it OK if we make lots of reading contract requests for each row of the list transfers responded? (List transfers will be polling)

**Comment by lzxm160** [comment]
> > we didn't store those infos,can call readcontract api directly
> 
> To read a contract, we would need `contractAddress` to be added to `Xrc20Info` as response of queries xrc20 `byPage` & `byAddress`. Could you please help recheck?

I think add contractAddress is ok,wait for @lizhefeng to confirm

**Comment by lizhefeng** [comment]
> Is it OK if we make lots of reading contract requests for each row of the list transfers responded? (List transfers will be polling)

What do you mean? @nmhung1210

**Comment by lizhefeng** [comment]
> > > we didn't store those infos,can call readcontract api directly
> > 
> > 
> > To read a contract, we would need `contractAddress` to be added to `Xrc20Info` as response of queries xrc20 `byPage` & `byAddress`. Could you please help recheck?
> 
> I think add contractAddress is ok,wait for @lizhefeng to confirm

@lzxm160 Please help add contract address to Xrc20Info

**Comment by lzxm160** [comment]
> > > > we didn't store those infos,can call readcontract api directly
> > > 
> > > 
> > > To read a contract, we would need `contractAddress` to be added to `Xrc20Info` as response of queries xrc20 `byPage` & `byAddress`. Could you please help recheck?
> > 
> > 
> > I think add contractAddress is ok,wait for @lizhefeng to confirm
> 
> @lzxm160 Please help add contract address to Xrc20Info

ok

**Comment by nmhung1210** [comment]
@lizhefeng should we need `ABI` of a contract to be able to read it? If yes then how to get `ABI` of a contract that deployed by our users? else how to read a contract without the `ABI`?

**Comment by lzxm160** [comment]
for xrc20,just call "06fdde03": "name()","95d89b41": "symbol()"

**Comment by lizhefeng** [comment]
@nmhung1210 It depends what you want to get from this API. If we only care about from address, to address, amount,  and contract address, the existing API serves it well without knowing about the ABI of the specific  XRC20 token.
