### ISSUE TITLE
Could not get xrc20 when pass variables

### ISSUE THREAD

**Issue by hunglmtb** [iotexproject/iotex-analytics#97]
we can get result of xrc20 when query without variable, like this 
```
query {
  xrc20 {
    byAddress(
      address: "io1crkagrkzypfmsjwthyccrhgk29rj6epsee4dsy"
      numPerPage: 10
      page: 1
    ) {
      exist
      xrc20 {
        hash
        from
        to
        quantity
        timestamp
      }
      count
    }
  }
}
```
![image](https://user-images.githubusercontent.com/11267061/65789705-255a7d80-e188-11e9-9bd1-56141299b44f.png)

However, when we pass variables, it returns error
```
query Xrc20Query($address: String!, $numPerPage: Int!, $page: Int!) {
  xrc20 {
    byAddress(address: $address, numPerPage: $numPerPage, page: $page) {
      exist
      count
      xrc20 {
      hash
      from
      to
      quantity
      timestamp
    }
    }
  }
}

{
  "address": "io1crkagrkzypfmsjwthyccrhgk29rj6epsee4dsy",
  "numPerPage": 10,
  "page": 1
}
```
![image](https://user-images.githubusercontent.com/11267061/65790134-1e803a80-e189-11e9-92a7-1793930255a0.png)

We need it working with apollo client have passing variables for iopay-android with apollo-android ...
refer #https://github.com/iotexproject/iotex-explorer/issues/994

**Comment by lzxm160** [comment]
Let me find out
